name: Build and Test Backend (api)

on:
  pull_request:
    branches:
      - main

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Make gradlew executable
        working-directory: api
        run: chmod +x ./gradlew

      - name: Build and run tests in api only
        working-directory: api
        run: ./gradlew clean build --no-daemon
